version: "2"
services:

  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  # otel-collector:
  #   image: ${OTELCOL_IMG}
  #   command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
  #   volumes:
  #     - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
  #   ports:
  #     - "1888:1888"   # pprof extension
  #     - "13133:13133" # health_check extension
  #     - "4317"        # OTLP gRPC receiver
  #     - "55670:55679" # zpages extension
  #   depends_on:
  #     - jaeger-all-in-one

  # Datadog Agent
  dd-agent:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_OTLP_CONFIG_LOGS_ENABLED=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_TAGS=env:dev
      - 'DOCKER_HOST=unix:///run/user/1000/podman/podman.sock'
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318
    ports:
      - "8126:8126"
      - "8125:8125/udp"
      - "8125:8125"
      - "8129:8129"
      - "8130:8130"
      - "9130:9130"
      - "8126:8126"
      - "8125:8125/udp"
      - "8125:8125"
      - "8129:8129"
      - "8130:8130"
      - "9130:9130" 
      - "4317:4317"
      - "4318:4318"
    volumes:
      - /run/user/1000/podman/podman.sock:/run/user/1000/podman/podman.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    depends_on:
      - jaeger-all-in-one

  demo-client:
    build:
      dockerfile: Dockerfile
      context: ./client
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=dd-agent:4317
      - DEMO_SERVER_ENDPOINT=http://demo-server:7080/hello
    depends_on:
      - demo-server

  demo-server:
    build:
      dockerfile: Dockerfile
      context: ./server
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=dd-agent:4317
    ports:
      - "7080"
    depends_on:
      - otel-collector
